# This file was generated by GoReleaser. DO NOT EDIT.
cask "hub-cli" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "db7a62cc0712512116313d4d102092d0b2b9b53b61704877c5e0065a11effd70"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "800b98eea37327ef5e73ba3f2b500a415b90629ac8ad5f3cf3028912cf1b9946"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4bc83d4b923f82755c55f4645abeb4b26b7ad798c0b2c570b4da6f70d3f3f665"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89357f0156b128664bdf0584a9aab62a01549793515d29747addf964be39aab2"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hub-cli"
  desc "Command-line client for the Briteweb Hub"
  homepage "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hub-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hub-cli"]
    end
  end

  # No zap stanza required
end
