# This file was generated by GoReleaser. DO NOT EDIT.
cask "hub-cli" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "d3e0b547c3c42293412aa949dae0137a027687ca49ea97eac42b0f89125cf811"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a597174e296444d8a2ba30bd8a31fb2eac3ec0ba5cb08a98d5fa53c883f7b7b"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a8fb7609b6f0b4ac80851ccd8a7e820ddd91a81a5739dc90a98ca9275d8e8bd4"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20bf46099e0a3da3f2f408ea20aa3f38e58ac9f23b245cbf91c676e770f7fa5e"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hub-cli"
  desc "Command-line client for the Briteweb Hub"
  homepage "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hub-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hub-cli"]
    end
  end

  # No zap stanza required
end
