# This file was generated by GoReleaser. DO NOT EDIT.
cask "hub-cli" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7eebaf0931c112b3c5393ddd0afb7d3b89c33752565cbd1584a3cdf48fc73149"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd1a025c0d91b7b3377b0054826f3eebcce1cb2a7120922aa7b84e8a8a7e2503"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5063dcf612fbaeca627db0c9d2f54f489af96b1a131729718e9aa5209662dff6"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ebcd7be738bf56fcde851ef493259573dec725bf6eee91ade7b979234470b75"
      url "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases/releases/download/v#{version}/hub-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hub-cli"
  desc "Command-line client for the Briteweb Hub"
  homepage "https://github.com/Briteweb-Ltd/briteweb-hub-cli-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hub-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hub-cli"]
    end
  end

  # No zap stanza required
end
